1. Create NumPy arrays with different methods (lists, zeros, ones, arange).
2. Perform mathematical operations on NumPy arrays (addition, subtraction, multiplication,
division).
3. Practice indexing and slicing NumPy arrays.
4. Use NumPy functions for basic statistical analysis like mean,median and mode.
5. Experiment with reshaping and transposing NumPy arrays

In [2]:
import numpy as np

In [3]:
#create numpy with different methods (list,zeros,ones,arange)

#list
l1 = [2,4,5,6,7,8,9]
n1 = np.array(l1)
print(n1)

#tuple
t1 = (1,2,3,4,5)
n3 = np.array(t1)
print(n3)

#zeros
z1 = np.zeros(10, int)
print(z1)

#ones
z2 = np.ones(5, int)
print(z2)

#arange
z3 = np.arange(5,10)
print(z3)

[2 4 5 6 7 8 9]
[1 2 3 4 5]
[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1]
[5 6 7 8 9]


In [4]:
#perform matthematical operations on numpy arrays

b1 = np.arange(10,21)
b2 = np.arange(20,31)
print(b1)
print(b2)

#addition
print("Addition of two arrays: ")
sum = b1 + b2
print(sum)

#subtraction
print("Subtraction of two arrays:")
sub = b1-b2
print(sub)

#multiplication
print("Multiplication of two arrays: ")
mul = b1*b2
print(mul)

#division
print("Division of two arrays:")
div = b1/b2
print(div)

[10 11 12 13 14 15 16 17 18 19 20]
[20 21 22 23 24 25 26 27 28 29 30]
Addition of two arrays: 
[30 32 34 36 38 40 42 44 46 48 50]
Subtraction of two arrays:
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Multiplication of two arrays: 
[200 231 264 299 336 375 416 459 504 551 600]
Division of two arrays:
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6
 0.61538462 0.62962963 0.64285714 0.65517241 0.66666667]


In [5]:
#practice indexing and slicing numpy arrays

#indexing
idx = b1[2]
print(idx)



#slicing
slc1 = b1[2:6]
slc2 = b1[:]
slc3 = b1[-6:-1:2]

print(slc1)
print(slc2)
print(slc3)

12
[12 13 14 15]
[10 11 12 13 14 15 16 17 18 19 20]
[15 17 19]


In [12]:
#use numpy functions for basic statistical analysis like mean,median,mode


# 1D array
a1 = np.array([1,2,3,4,5])
print(a1)

# 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

# 3D array
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a3)

#mean
print(np.mean(a2))
print(np.mean(a2,axis=0))
print(np.mean(a2,axis=1))


#median
print("Median of a1 ",np.median(a1))
print("Median of a2 ", np.median(a2))
print("Median of a3 ", np.median(a3))


#mode
from scipy import stats as st
print("Mode of a1 ",st.mode(a1))
print("Mode of a2 ",st.mode(a2))
print("Mode of a3 ",st.mode(a3))


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3.5
[2.5 3.5 4.5]
[2. 5.]
Median of a1  3.0
Median of a2  3.5
Median of a3  6.5
Mode of a1  ModeResult(mode=1, count=1)
Mode of a2  ModeResult(mode=array([1, 2, 3], dtype=int64), count=array([1, 1, 1], dtype=int64))
Mode of a3  ModeResult(mode=array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64), count=array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64))


In [9]:
# experiment eith reshaping and transposing numpy arrays
a2 = np.array([1,2,3,4,5,6,7,8,9,10])

#reshaping
print("Reshaping a2")
res = a2.reshape(2,5)
print(res)

#transposing
print("Transposing a2")
trans = a2.transpose()
print(trans)


Reshaping a2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Transposing a2
[ 1  2  3  4  5  6  7  8  9 10]
